table MasterData_Columns
	lineageTag: e8a1f2e1-4567-48b2-a1f9-d1f855e90a22

	column Phong_Nhom
		dataType: string
		lineageTag: c9475224-7ea2-4812-af44-fdf822d3b7d7
		summarizeBy: none
		sourceColumn: Phong_Nhom

		annotation SummarizationSetBy = Automatic

	column Col_Index
		dataType: int64
		formatString: 0
		lineageTag: c9475224-7ea2-4812-af44-fdf822d3b7d8
		summarizeBy: none
		sourceColumn: Col_Index

		annotation SummarizationSetBy = Automatic

	column Col_Header
		dataType: string
		lineageTag: c9475224-7ea2-4812-af44-fdf822d3b7d9
		summarizeBy: none
		sourceColumn: Col_Header

		annotation SummarizationSetBy = Automatic

	partition MasterData_Columns = m
		mode: import
		source =
				let
				    Source = Table.FromRows({
				        {"9.1 HRC - NHÂN SỰ", 1, "1. Tổng định biên"},
				        {"9.1 HRC - NHÂN SỰ", 2, "2. Đang làm việc"},
				        {"9.1 HRC - NHÂN SỰ", 3, "3. Sẽ tuyển"},
				        {"9.1 HRC - NHÂN SỰ", 4, "4. Chi tiết"},
				        {"9.1 HRC - NHÂN SỰ", 5, "5. Ghi chú"},
				
				        {"9.2 FAC", 1, "1. Đã có TBTD"},
				        {"9.2 FAC", 2, "2. Chưa có TBTD"},
				        {"9.2 FAC", 3, "3. Dự kiến có TBTD"},
				        {"9.2 FAC", 4, "4. Chi tiết"},
				        {"9.2 FAC", 5, "5. Ghi chú"},
				
				        {"9.3 SAC - BÁN HÀNG", 1, "1. Đã bán (Ký HĐMB/Tổng số)"},
				        {"9.3 SAC - BÁN HÀNG", 2, "2. Chưa bán"},
				        {"9.3 SAC - BÁN HÀNG", 3, "3. Dự kiến bán"},
				        {"9.3 SAC - BÁN HÀNG", 4, "4. Chi tiết"},
				        {"9.3 SAC - BÁN HÀNG", 5, "5. Ghi chú"},
				
				        {"9.4 MAC - SALE KIT / SỰ KIỆN", 1, "1. Sale kit"},
				        {"9.4 MAC - SALE KIT / SỰ KIỆN", 2, "2. Sự kiện"},
				        {"9.4 MAC - SALE KIT / SỰ KIỆN", 3, "3. Ngày tổ chức"},
				        {"9.4 MAC - SALE KIT / SỰ KIỆN", 4, "4. Chi tiết"},
				        {"9.4 MAC - SALE KIT / SỰ KIỆN", 5, "5. Ghi chú"},
				
				        {"9.5 PTC - KẾ HOẠCH CƯĐT", 1, "1. Mục"},
				        {"9.5 PTC - KẾ HOẠCH CƯĐT", 2, "2. Hiện trạng KH CUĐT"},
				        {"9.5 PTC - KẾ HOẠCH CƯĐT", 3, "3. Điều chỉnh"},
				        {"9.5 PTC - KẾ HOẠCH CƯĐT", 4, "4. Ngày hoàn thành"},
				        {"9.5 PTC - KẾ HOẠCH CƯĐT", 5, "5. Chi tiết"},
				        {"9.5 PTC - KẾ HOẠCH CƯĐT", 6, "6. Ghi chú"},
				
				        {"9.6 QSB - NGÂN SÁCH", 1, "1. Mục"},
				        {"9.6 QSB - NGÂN SÁCH", 2, "2. Hiện trạng"},
				        {"9.6 QSB - NGÂN SÁCH", 3, "3. Điều chỉnh"},
				        {"9.6 QSB - NGÂN SÁCH", 4, "4. Ngày hoàn thành"},
				        {"9.6 QSB - NGÂN SÁCH", 5, "5. Chi tiết"},
				        {"9.6 QSB - NGÂN SÁCH", 6, "6. Ghi chú"},
				
				        {"9.7 SEC - AN NINH", 1, "1. Đã có PA"},
				        {"9.7 SEC - AN NINH", 2, "2. Chưa có PA"},
				        {"9.7 SEC - AN NINH", 3, "3. Ngày hoàn thành"},
				        {"9.7 SEC - AN NINH", 4, "4. Chi tiết"},
				        {"9.7 SEC - AN NINH", 5, "5. Ghi chú"},
				
				        {"9.8 IDD - THIẾT KẾ NỘI BỘ", 1, "1. Mục"},
				        {"9.8 IDD - THIẾT KẾ NỘI BỘ", 2, "2. Hiện trạng hồ sơ"},
				        {"9.8 IDD - THIẾT KẾ NỘI BỘ", 3, "3. Điều chỉnh"},
				        {"9.8 IDD - THIẾT KẾ NỘI BỘ", 4, "4. Ngày hoàn thành"},
				        {"9.8 IDD - THIẾT KẾ NỘI BỘ", 5, "5. Chi tiết"},
				        {"9.8 IDD - THIẾT KẾ NỘI BỘ", 6, "6. Ghi chú"},
				
				        {"9.9 CSC - BỒI THƯỜNG, GPMB", 1, "1. Có thực hiện"},
				        {"9.9 CSC - BỒI THƯỜNG, GPMB", 2, "2. Không thực hiện"},
				        {"9.9 CSC - BỒI THƯỜNG, GPMB", 3, "3. Ngày hoàn thành"},
				        {"9.9 CSC - BỒI THƯỜNG, GPMB", 4, "4. Chi tiết"},
				        {"9.9 CSC - BỒI THƯỜNG, GPMB", 5, "5. Ghi chú"},
				
				        {"4.0 PMD - MASTER TIMELINE", 1, "1. Mục"},
				        {"4.0 PMD - MASTER TIMELINE", 2, "2. Hiện trạng MTL"},
				        {"4.0 PMD - MASTER TIMELINE", 3, "3. Điều chỉnh"},
				        {"4.0 PMD - MASTER TIMELINE", 4, "4. Ngày hoàn thành"},
				        {"4.0 PMD - MASTER TIMELINE", 5, "5. Chi tiết"},
				        {"4.0 PMD - MASTER TIMELINE", 6, "6. Ghi chú"},
				
				        {"4.1 PLP", 1, "1. Mục"},
				        {"4.1 PLP", 2, "2. Nội dung"},
				        {"4.1 PLP", 3, "3. Văn bản phê duyệt"},
				        {"4.1 PLP", 4, "4. Khó khăn/ Vướng mắc"},
				        {"4.1 PLP", 5, "5. Hướng xử lý"},
				        {"4.1 PLP", 6, "6. Ngày hoàn thành"},
				        {"4.1 PLP", 7, "7. Chi tiết"},
				
				        {"4.2 DMD", 1, "1. Mục"},
				        {"4.2 DMD", 2, "2. Hiện trạng hồ sơ"},
				        {"4.2 DMD", 3, "3. Điều chỉnh"},
				        {"4.2 DMD", 4, "4. Ngày hoàn thành"},
				        {"4.2 DMD", 5, "5. Chi tiết"},
				        {"4.2 DMD", 6, "6. Ghi chú"},
				
				        {"4.3 PCD", 1, "1. Mục"},
				        {"4.3 PCD", 2, "2. Hiện trạng thi công (%)"},
				        {"4.3 PCD", 3, "3. Ngày hoàn thành"},
				        {"4.3 PCD", 4, "4. Chi tiết"},
				        {"4.3 PCD", 5, "5. Ghi chú"},
				
				        {"4.4 PM", 1, "1. Đã bàn giao (Giao/Tổng số)"},
				        {"4.4 PM", 2, "2. Chưa bàn giao"},
				        {"4.4 PM", 3, "3. Ngày hoàn thành"},
				        {"4.4 PM", 4, "4. Chi tiết"},
				        {"4.4 PM", 5, "5. Ghi chú"}
				    }, type table [Phong_Nhom = text, Col_Index = Int64.Type, Col_Header = text])
				in
				    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

